public void root_change(GTextField source, GEvent event) {}

public void textfield1_change2(GTextField source, GEvent event) {}

public void display_click(GButton source, GEvent event) {
  double value = rootIt(Double.parseDouble(root.getText()), Double.parseDouble(number.getText()));
  textfield2.setText(Double.toString(value));
}

public void textfield2_change1(GTextField source, GEvent event) {}



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Root It!");
  root = new GTextField(this, 10, 20, 20, 20, G4P.SCROLLBARS_NONE);
  root.setOpaque(true);
  root.addEventHandler(this, "root_change");
  number = new GTextField(this, 47, 22, 40, 40, G4P.SCROLLBARS_NONE);
  number.setOpaque(true);
  number.addEventHandler(this, "textfield1_change2");
  display = new GButton(this, 10, 110, 80, 30);
  display.setText("calculate");
  display.addEventHandler(this, "display_click");
  textfield2 = new GTextField(this, 10, 70, 80, 30, G4P.SCROLLBARS_NONE);
  textfield2.setOpaque(true);
  textfield2.addEventHandler(this, "textfield2_change1");
}

// Variable declarations 
// autogenerated do not edit
GTextField root; 
GTextField number; 
GButton display; 
GTextField textfield2; 
